// react/src/components/CompleteAll.tsx
import React, { Component } from 'react';
import { ICompleteAllView, Injector, CompleteAllMixin, CompleteAllPresenter } from '../core';

interface ICompleteAllState {
  isChecked: boolean;
};

export default class CompleteAll extends CompleteAllMixin(Component)<{}, ICompleteAllState> implements ICompleteAllView {
  public readonly presenter: CompleteAllPresenter = Injector.resolve(CompleteAllPresenter);
  private isUmounting: boolean = false;

  public get isChecked(): boolean {
    return this.state ? this.state.isChecked : false;
  }

  public check(): void {
    if (this.isUmounting) {
      return;
    }
    this.setState({
      isChecked: true
    });
  }

  public uncheck(): void {
    if (this.isUmounting) {
      return;
    }
    this.setState({
      isChecked: false
    });
  }

  public componentDidMount():void {
    this.presenter.attach(this);
  }

  public componentWillUnmount(): void {
    this.isUmounting = true;
  }

  render() {
    return (
      <input id="toggle-all"
             className="toggle-all"
             type="checkbox"
             onChange={() => {}}
             onClick={() => this.onCompleteAllClicked()}
             checked={this.isChecked} />
    )
  }
}

// vue/src/components/CompleteAll.vue
<template>
  <input id="toggle-all" class="toggle-all" type="checkbox" :checked="isChecked" v-on:click="onCompleteAllClicked">
</template>

<script lang="ts">
import { Component } from 'vue-property-decorator';
import { Injector, ICompleteAllView, CompleteAllPresenter } from '../../../app/src';
import { VueCompleteAllMixin } from '../mixins';

@Component({
  mixins: [VueCompleteAllMixin],
})
export default class CompleteAll extends VueCompleteAllMixin implements ICompleteAllView {
  public isChecked: boolean = false;

  public readonly presenter: CompleteAllPresenter = Injector.resolve(CompleteAllPresenter);

  public created(): void {
    this.presenter.attach(this);
  }

  public check(): void {
    this.isChecked = true;
  }

  public uncheck(): void {
    this.isChecked = false;
  }
}
</script>
