// angular/src/app/footer/filter-link/filter-link.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { Injector, FilterLinkMixin, IFilterLinkView, FilterLinkPresenter, TodoFilterType } from '../../../../../app/src';
import { BaseView } from '../../base.view';

@Component({
  selector: '[app-filter-link]',
  templateUrl: 'filter-link.template.html',
  styles: []
})
export class FilterLinkComponent extends FilterLinkMixin(BaseView) implements IFilterLinkView, OnInit {
  @Input()
  public filter: TodoFilterType;

  public isSelected: boolean = false;

  public readonly presenter: FilterLinkPresenter = Injector.resolve(FilterLinkPresenter);

  public ngOnInit(): void {
    this.presenter.attach(this);
  }

  public select(): void {
    this.isSelected = true;
  }

  public unselect(): void {
    this.isSelected = false;
  }
}

// vue/src/components/FilterLink.vue
<template>
  <li>
    <a :class="{'selected': isSelected}" v-on:click="onLinkClicked()" href="#"><slot></slot></a>
  </li>
</template>

<script lang="ts">
import { Component, Prop } from 'vue-property-decorator';
import { Injector, IFilterLinkView, FilterLinkPresenter, TodoFilterType } from '../../../app/src';
import { VueFilterLinkMixin } from '../mixins';

@Component({
  mixins: [VueFilterLinkMixin],
})
export default class FilterLink extends VueFilterLinkMixin implements IFilterLinkView {
  @Prop()
  public filter!: TodoFilterType;

  public isSelected: boolean = false;

  public readonly presenter: FilterLinkPresenter = Injector.resolve(FilterLinkPresenter);

  public created(): void {
    this.presenter.attach(this);
  }

  public select(): void {
    this.isSelected = true;
  }

  public unselect(): void {
    this.isSelected = false;
  }
}
</script>
