// react/src/components/Header.tsx
import React, { Component, ChangeEvent, KeyboardEvent } from 'react';
import { IHeaderView, Injector, HeaderMixin, HeaderPresenter } from '../core';

interface IHeaderState {
  input: string;
};

export default class Header extends HeaderMixin(Component)<{}, IHeaderState> implements IHeaderView {
  public readonly presenter: HeaderPresenter = Injector.resolve(HeaderPresenter);

  public get todoTitleInput(): string {
    return this.state ? this.state.input : '';
  }

  public emptyTodoInput(): void {
    this.setState({
      input: ''
    });
  }

  public onChange(event: ChangeEvent<HTMLInputElement>): void {
    this.setState({
      input: event.target.value
    });
  }

  public onKeyDown(event: KeyboardEvent<HTMLInputElement>): void {
    if (event.key === 'Enter') {
      this.onAddTodo(this.state.input);
    }
  }

  public componentDidMount():void {
    this.presenter.attach(this);
  }

  render() {
    return (
      <header className="header">
        <h1>todos</h1>
        <input className="new-todo"
               placeholder="What needs to be done?"
               onChange={event => this.onChange(event)}
               onKeyDown={event => this.onKeyDown(event)}
               value={this.todoTitleInput}
               autoFocus={true} />
      </header>
    )
  }
}

// vue/src/components/Header.vue
<template>
  <header class="header">
    <h1>todos</h1>
    <input v-model="todoTitleInput" v-on:keyup.enter="onAddTodo(todoTitleInput)" class="new-todo" placeholder="What needs to be done?" autofocus>
  </header>
</template>

<script lang="ts">
import { Component } from 'vue-property-decorator';
import { HeaderPresenter, Injector, IHeaderView } from '../../../app/src';
import { VueHeaderMixin } from '../mixins';

@Component({
  mixins: [VueHeaderMixin],
})
export default class Header extends VueHeaderMixin implements IHeaderView {
  public todoTitleInput: string = '';

  public readonly presenter: HeaderPresenter = Injector.resolve(HeaderPresenter);

  public created(): void {
    this.presenter.attach(this);
  }

  public emptyTodoInput(): void {
    this.todoTitleInput = '';
  }
}
</script>
