// vue/src/components/Footer.vue
<template>
  <footer class="footer">
      <span class="todo-count"><strong>{{ activeTodoCount }}</strong> {{ 'item' | pluralize(activeTodoCount) }} left</span>
      <ul class="filters">
        <li>
          <router-link :to="{ name: 'home'}" exact>All</router-link>
        </li>
        <li>
          <router-link :to="{ name: 'active'}" exact>Active</router-link>
        </li>
        <li>
          <router-link :to="{ name: 'completed'}" exact>Completed</router-link>
        </li>
      </ul>
      <button v-if="isClearCompletedLinkShown" v-on:click="onClearCompletedClicked()" class="clear-completed">Clear completed</button>
    </footer>
</template>

<script lang="ts">
import { Component, Vue } from 'vue-property-decorator';
import { FooterPresenter, Injector, IFooterView, TodoFilterType } from '../../../app/src';
import { VueFooterMixin } from '../mixins';

@Component({
  mixins: [VueFooterMixin]
})
export default class Footer extends VueFooterMixin implements IFooterView {
  public activeTodoCount: number = 0;
  public noneFilter: TodoFilterType = 'none';
  public activeFilter: TodoFilterType = 'active';
  public completedFilter: TodoFilterType = 'completed';
  public isClearCompletedLinkShown: boolean = false;

  public readonly presenter: FooterPresenter = Injector.resolve(FooterPresenter);

  public created(): void {
    this.presenter.attach(this);
  }

  public setActiveTodoCount(count: number): void {
    this.activeTodoCount = count;
  }

  public showClearCompletedLink(): void {
    this.isClearCompletedLinkShown = true;
  }

  public hideClearCompletedLink(): void {
    this.isClearCompletedLinkShown = false;
  }
}
</script>

// react/src/components/Footer.tsx
import React, { Component } from 'react';
import { NavLink } from 'react-router-dom';

import { IFooterView, Injector, FooterMixin, FooterPresenter } from '../core';

interface IFooterState {
  activeTodoCount: number;
  isClearCompletedLinkShown: boolean;
};

export default class Footer extends FooterMixin(Component)<{}, IFooterState> implements IFooterView {
  public readonly presenter: FooterPresenter = Injector.resolve(FooterPresenter);
  private isUmounting: boolean = false;

  public get activeTodoCount(): number {
    return this.state ? this.state.activeTodoCount : 0;
  }

  public get isClearCompletedLinkShown(): boolean {
    return this.state ? this.state.isClearCompletedLinkShown : false;
  }

  public setActiveTodoCount(count: number): void {
    if (this.isUmounting) {
      return;
    }
    this.setState({
      activeTodoCount: count
    });
  }

  public showClearCompletedLink(): void {
    if (this.isUmounting) {
      return;
    }
    this.setState({
      isClearCompletedLinkShown: true
    });
  }

  public hideClearCompletedLink(): void {
    if (this.isUmounting) {
      return;
    }
    this.setState({
      isClearCompletedLinkShown: false
    });
  }

  public componentDidMount():void {
    this.presenter.attach(this);
  }

  public componentWillUnmount(): void {
    this.isUmounting = true;
  }

  render() {
    const clearButton = this.isClearCompletedLinkShown
      ? (<button onClick={() => this.onClearCompletedClicked()} className="clear-completed">Clear completed</button>)
      : '';
    const itemWord = this.activeTodoCount === 1 ? 'item' : 'items';
    return (
      <footer className="footer">
        <span className="todo-count"><strong>{ this.activeTodoCount }</strong> {itemWord} left</span>
        <ul className="filters">
          <li>
            <NavLink exact={true} activeClassName="selected" to="/">All</NavLink>
          </li>
          <li>
            <NavLink exact={true} activeClassName="selected" to="/active">Active</NavLink>
          </li>
          <li>
            <NavLink exact={true} activeClassName="selected" to="/completed">Completed</NavLink>
          </li>
        </ul>
        {clearButton}
      </footer>
    )
  }
}
